# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api_doc:
            pattern:      ^/api/doc
            security:     false
        api:
            pattern: ^/                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
#            anonymous: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/group, roles: ROLE_ADMIN }